import time
import sys
def escrever_devagar(texto, velocidade=0.05):
    for letra in texto:
        sys.stdout.write(letra)
        sys.stdout.flush()
        time.sleep(velocidade)
    print()
print("=========================== EXAME DE CONCIÊNCIA ===========================")
print("===========================================================================")
time.sleep(1)
escrever_devagar("\n\033[34mSe queres entrar para a vida eterna, guarda os\nMandamentos. (Mt 19, 16-17)\033[0m")
escrever_devagar(" \n                                   AVISO")
time.sleep(1)
escrever_devagar("\nEste exame de consciência tem como objetivo ajudá-lo(a) a recordar possíveis faltas e refletir sobre sua vida espiritual.")
time.sleep(1)
escrever_devagar("\nA análise da gravidade dos pecados é algo pessoal e deve ser feita com consciência, responsabilidade e, se necessário, com a orientação de um sacerdote.")
time.sleep(1)
escrever_devagar("\n \033[31mEste guia não contém todos os pecados possíveis.\nPor isso, é importante rezar e pedir a Deus, especialmente ao Espírito Santo, \nque ilumine sua mente e seu coração, ajudando-o(a) a reconhecer com sinceridade aquilo que precisa ser mudado.\033[0m")
time.sleep(0.5)
escrever_devagar("\n Use este exame com humildade, sinceridade e desejo de conversão.")
time.sleep(1)
escrever_devagar("\033[33m\n\nVale lembrar que nem todo pecado é Mortal.\n\nPara que um pecado seja considerado grave (mortal), é necessário que estejam presentes três condições:\n\n1. Matéria grave: a ação envolve algo seriamente contrário à lei de Deus (como os mandamentos).\n2. Pleno conhecimento: a pessoa sabe que aquilo é pecado grave.\n3. Consentimento deliberado: a pessoa escolhe livremente cometer o ato.\n\nSe uma dessas condições não estiver presente, o pecado pode não ser considerado grave.\n\nEste exame tem como objetivo ajudar na reflexão, mas a consciência pessoal e a orientação espiritual são essenciais.\033[0m")
time.sleep(2)
escrever_devagar("                \n----- NÃO ESQUEÇA DE ANOTAR SEUS PECADOS -----")
time.sleep(2)
print("\n \n-------------------- PRIMEIRO MANDAMENTO DA LEI DE DEUS ----------------------")
escrever_devagar("\n Amar a Deus sobre todas as coisas")
time.sleep(1)
escrever_devagar("\n \n \033[35mTenho posto em dúvida alguma verdade de fé? Critiquei algum ensinamento da Igreja?\033[0m")
time.sleep(1)
escrever_devagar("\n \033[35mRezo diariamente? Distraio-me voluntariamente nas orações?\033[0m")
time.sleep(0.5)
escrever_devagar("\n\033[35mDeixei-me levar pelo desânimo? Revoltei-me contra Deus?\033[0m")
time.sleep(0.5)
escrever_devagar("\n\033[35mFrequentei lugares ou cultos contrários à fé católica?\n Fiz coisas supersticiosas? Consultei “videntes”, feiticeiros, benzedores, \ncartomantes, etc.?\033[0m")
time.sleep(0.5)
escrever_devagar("\n\033[35mTenho sido orgulhoso ou vaidoso? Sou teimoso, arrogante ou malcriado? Sou invejoso?\033[0m")
time.sleep(0.5)
escrever_devagar("\n\033[35mSou avarento passando o dia inteiro a pensar em dinheiro ou em obter coisas?\033[0m")
time.sleep(0.5)
escrever_devagar("\n\033[35mTenho-me demorado em pensamentos sobre mim, exagerando as minhas qualidades?\033[0m")
time.sleep(1)
print("===================================================================================")
print("==================================================================================")
print("------------------------------- FAÇA AS SUAS ANOTAÇÕES ----------------------------")
time.sleep(1.6)
input("APÓS FAZER SUAS ANOTAÇÕES APERTE (ENTER) PARA CONTINUAR")
print("\n \n------------------------SEGUNDO MANDAMENTO DA LEI DE DEUS --------------------------")
time.sleep(1)
print("\n  Não invocar o Santo Nome de Deus em vão")
time.sleep(1)
escrever_devagar("\n\033[35mTenho pronunciado sem respeito o nome de Deus ou dos Santos?\033[0m")
time.sleep(0.5)
escrever_devagar("\n\033[35mFalei sem respeito das coisas sagradas, da Igreja, ou de sacerdotes?\n Permiti que outros o fizessem na minha presença? Ridicularizei padres, \nfreiras, religiosos, catequistas, etc.?\033[0m")
time.sleep(0.5)
escrever_devagar("\n\033[35mTenho jurado à toa ou jurado falso?\033[0m")
time.sleep(0.5)
escrever_devagar("\n\033[35mDeixei de cumprir alguma promessa que fiz?\033[0m")
time.sleep(1)
print("\n===================================================================================")
print("==================================================================================")
print("------------------------------- FAÇA AS SUAS ANOTAÇÕES ----------------------------")
time.sleep(1.6)
input("APÓS FAZER SUAS ANOTAÇÕES APERTE (ENTER) PARA CONTINUAR")
print("\n \n------------------------TERCEIRO MANDAMENTO DA LEI DE DEUS --------------------------")
time.sleep(1)
print("\n Santificar os domingos e festas de gaurda")
time.sleep(1)
escrever_devagar("\n\033[35mFaltei à Missa em algum domingo ou dia santo? \nImpedi que alguém que dependesse de mim a assistisse?\n Cheguei atrasado à Eucaristia por culpa própria?\033[0m")
time.sleep(0.6)
escrever_devagar("\n\033[35mCumpri o preceito do descanso nos domingos e festas de guarda? Obriguei outros a trabalharem?\033[0m")
time.sleep(0.5)
escrever_devagar("\n\033[35mTenho deixado de me confessar? Escondi algum pecado na Confissão?\033[0m")
time.sleep(0.5)
escrever_devagar("\n\033[35mCumpri o preceito de receber a Comunhão pelo menos uma vez ao ano no período da Páscoa?\033[0m")
time.sleep(0.5)
escrever_devagar("\n\033[35mComunguei alguma vez consciente de um pecado mortal não confessado?\033[0m")
time.sleep(0.5)
escrever_devagar("\n\033[35mTenho-me apresentado para a Sagrada Comunhão com espírito frio e pouco recolhido?\033[0m")
time.sleep(0.5)
escrever_devagar("\n\033[35mContribuo para as necessidades da Igreja segundo as minhas possibilidades?\033[0m")
time.sleep(0.5)
escrever_devagar("\n\033[35mGuardei a abstinência de carne nas sextas-feiras? Jejuei Quarta-feira de cinzas e Sexta-feira Santa?\033[0m")
time.sleep(1)
print("\n===================================================================================")
print("==================================================================================")
print("------------------------------- FAÇA AS SUAS ANOTAÇÕES ----------------------------")
time.sleep(1.6)
input("APÓS FAZER SUAS ANOTAÇÕES APERTE (ENTER) PARA CONTINUAR")
print("\n \n------------------------QUARTO MANDAMENTO DA LEI DE DEUS --------------------------")
time.sleep(1)
print("\n Honrar pai, mãe e legítimos superiores")
time.sleep(1)
escrever_devagar("\n\033[35mFaltei à obediência aos meus pais e superiores? Faltei-lhes ao respeito?\033[0m")
time.sleep(0.5)
escrever_devagar("\n\033[35mDeixei de lhes manifestar o devido amor? Deixei de ajudá-los espiritual e materialmente?\033[0m")
time.sleep(0.5)
escrever_devagar("\n\033[35mZanguei-me com a minha esposa (com o meu marido)? Tratei-a(o) mal por palavras ou ações?\033[0m")
time.sleep(0.5)
escrever_devagar("\n\033[35mDei mau exemplo aos meus filhos ou subordinados,\n não cumprindo os meus deveres religiosos, familiares, sociais ou profissionais?\033[0m")
time.sleep(0.5)
escrever_devagar("\n\033[35mAo corrigir os meus filhos deixo-me dominar pela ira? \nOmito repreensões ou advertências que sei serem necessárias para a formação deles?\n Regulei o uso que fazem da televisão, internet, celular, revistas e\n outros instrumentos que podem apresentar algum risco para a sua formação moral?\033[0m")
time.sleep(0.5)
escrever_devagar("\n\033[35mDescuidei-me de dar aos filhos a formação religiosa? Atrasei o Batismo ou a Primeira Comunhão deles por negligência?\033[0m")
time.sleep(0.5)
escrever_devagar("\n\033[35mDeixei de ajudar, dentro das minhas possibilidades, os meus familiares nas suas necessidades espirituais ou materiais?\033[0m")
time.sleep(0.5)
time.sleep(1)
print("\n===================================================================================")
print("==================================================================================")
print("------------------------------- FAÇA AS SUAS ANOTAÇÕES ----------------------------")
time.sleep(1.6)
input("APÓS FAZER SUAS ANOTAÇÕES APERTE (ENTER) PARA CONTINUAR")
print("\n \n------------------------ QUINTO MANDAMENTO DA LEI DE DEUS --------------------------")
time.sleep(1)
print("\n Não matar, nem causar, a si ou ao próximo, dano ao corpo ou à alma")
time.sleep(1)
escrever_devagar("\n\033[35mTive inimizade, ódio ou rancor contra alguém? Era meu familiar?\033[0m")
time.sleep(0.4)
escrever_devagar("\n\033[35mFiz ou desejei mal a alguém? Aconselhei alguém a fazê-lo?\n Insultei alguém? Alegrei-me com as desgraças alheias? Tive inveja de alguém?\033[0m")
time.sleep(0.4)
escrever_devagar("\n\033[35mDeixei de perdoar as ofensas que recebi?\033[0m")
time.sleep(0.4)
escrever_devagar("\n\033[35mDesleixei-me quanto à minha saúde? Atentei contra a minha vida? Desejei morrer?\033[0m")
time.sleep(0.4)
escrever_devagar("\n\033[35mFiz, aconselhei ou facilitei a alguém a praticar o aborto ou a eutanásia?\033[0m")
time.sleep(0.4)
escrever_devagar("\n\033[35mPrejudiquei a minha saúde embriagando-me ou comendo em excesso? Fiz uso de drogas?\033[0m")
time.sleep(0.4)
escrever_devagar("\n\033[35mCheguei a ferir ou tirar a vida do próximo? Fui imprudente ao dirigir automóveis?\033[0m")
time.sleep(0.4)
escrever_devagar("\n\033[35mPreocupei-me com o próximo, advertindo-o de algum grave perigo material ou espiritual?\033[0m")
time.sleep(0.4)
escrever_devagar("\n\033[35mTive mau convívio, por culpa própria, com os meus familiares, amigos ou conhecidos?\033[0m")
time.sleep(0.4)
escrever_devagar("\n\033[35mDisse palavrões? Dei escândalo?\033[0m")
time.sleep(0.4)
escrever_devagar("\n\033[35mPor preguiça, deixei de me levantar à hora devida?\033[0m")
time.sleep(1)
print("\n===================================================================================")
print("==================================================================================")
print("------------------------------- FAÇA AS SUAS ANOTAÇÕES ----------------------------")
time.sleep(1.6)
input("APÓS FAZER SUAS ANOTAÇÕES APERTE (ENTER) PARA CONTINUAR")
print("\n \n------------------------ 6º e 9º Mandamentos --------------------------")
time.sleep(1)
print("\n Guardar a castidade nas palavras, obras, pensamentos e desejos")
time.sleep(0.5)
escrever_devagar("\n\033[35mVi coisas indecentes? (na rua, na internet, no celular, na TV, em revistas ou em filmes)\033[0m")
time.sleep(0.5)
escrever_devagar("\n\033[35mTenho pensado ou desejado coisas impuras?\033[0m")
time.sleep(0.5)
escrever_devagar("\n\033[35mPratiquei ações impuras? Sozinho ou acompanhado?\033[0m")
time.sleep(0.5)
escrever_devagar("\n\033[35mHavia alguma circunstância na ação impura – de parentesco, pessoa casada, \nconsagrada a Deus ou menor de idade – que tornou mais grave aquela ação?\033[0m")
time.sleep(0.5)
escrever_devagar("\n\033[35mOlhei para alguém com intenção de obter um prazer impuro?\033[0m")
time.sleep(0.5)
escrever_devagar("\033[35mTive liberdades no namoro?\033[0m")
time.sleep(0.5)
escrever_devagar("\n\033[35mFaltei à fidelidade conjugal por pensamentos ou ações?\033[0m")
time.sleep(0.5)
escrever_devagar("\n\033[35mDei atenção a conversas imorais ou participei delas?\033[0m")
time.sleep(0.5)
escrever_devagar("\n\033[35mMantenho amizades que me levam ao pecado? Estou disposto a abandoná-las?\033[0m")
time.sleep(0.5)
escrever_devagar("\n\033[35mTenho faltado ao pudor, despindo-me levianamente à vista de outra pessoa?\033[0m")
time.sleep(0.5)
escrever_devagar("\n\033[35mVisto-me com modéstia ou utilizo roupas que realçam algumas partes do corpo?\033[0m")
time.sleep(0.5)
escrever_devagar("\n\033[35mAssisti a espetáculos, li revistas, livros \nou mensagens que me colocaram em ocasião próxima de pecar?\033[0m")
time.sleep(1)
print("\n===================================================================================")
print("==================================================================================")
print("------------------------------- FAÇA AS SUAS ANOTAÇÕES ----------------------------")
time.sleep(1.6)
input("APÓS FAZER SUAS ANOTAÇÕES APERTE (ENTER) PARA CONTINUAR")
print("\n \n------------------------ 7º e 10º Mandamentos --------------------------")
time.sleep(1)
print("\n Não furtar, nem reter injustamente ou danificar os bens do próximo. Não cobiçar as coisas alheias")
time.sleep(0.5)
escrever_devagar("\n\033[35mRoubei algum objeto ou alguma quantia em dinheiro? Ajudei alguém a roubar?\033[0m")
time.sleep(0.5)
escrever_devagar("\n\033[35mTive inveja dos outros, dos seus bens, das suas qualidades pessoais?\033[0m")
time.sleep(0.5)
escrever_devagar("\n\033[35mPaguei o justo salário aos empregados? \nRetenho ou atraso indevidamente o pagamento de bens e serviços? Lesei alguém nos seus direitos?\033[0m")
time.sleep(0.5)
escrever_devagar("\n\033[35mReparei os prejuízos causados ou restituí as coisas roubadas na medida das minhas possibilidades?\033[0m")
time.sleep(0.5)
escrever_devagar("\n\033[35mTrabalhei com empenho as horas que devia, ou desperdicei tempo no meu trabalho?\033[0m")
time.sleep(0.5)
escrever_devagar("\n\033[35mPrejudiquei alguém com enganos, coações, etc., nos contratos ou relações comerciais?\033[0m")
time.sleep(0.5)
escrever_devagar("\n\033[35mGastei mais do que permitem as minhas possibilidades? Tenho o vício do jogo?\033[0m")
time.sleep(1)
print("\n===================================================================================")
print("==================================================================================")
print("------------------------------- FAÇA AS SUAS ANOTAÇÕES ----------------------------")
time.sleep(1.6)
input("APÓS FAZER SUAS ANOTAÇÕES APERTE (ENTER) PARA CONTINUAR")
print("\n \n------------------------ 8º Mandamento --------------------------")
time.sleep(1)
print("\n Não mentir. Não levantar falsos testemunhos, nem difamar o próximo")
time.sleep(0.5)
escrever_devagar("\n\033[35mMenti? Reparei os prejuízos que as minhas mentiras possam ter causado?\033[0m")
time.sleep(0.5)
escrever_devagar("\n\033[35mMinto habitualmente com a desculpa de que se trata de mentiras que não prejudicam ninguém?\033[0m")
time.sleep(0.5)
escrever_devagar("\n\033[35mPrestei falso juramento ou dei falso testemunho?\033[0m")
time.sleep(0.5)
escrever_devagar("\n\033[35mDifamei, revelando sem motivo justo os defeitos alheios?\033[0m")
time.sleep(0.5)
escrever_devagar("\n\033[35mCaluniei, atribuindo ao próximo defeitos falsos? Exagerei os defeitos do próximo?\033[0m")
time.sleep(0.5)
escrever_devagar("\n\033[35mDisse mal dos outros, baseando-me apenas em boatos? Fiz juízos falsos ou temerários?\033[0m")
time.sleep(0.5)
escrever_devagar("\n\033[35mSemeei discórdias e inimizades com as minhas palavras?\033[0m")
time.sleep(0.5)
escrever_devagar("\n\033[35mPermiti que outros falassem mal do próximo? Escutei com gosto tais conversas?\033[0m")
time.sleep(0.5)
escrever_devagar("\n\033[35mProcurei reparar os prejuízos causados pelas minhas palavras\n (pela calúnia, difamação, etc.), por exemplo, falando dos aspetos positivos dessa pessoa?\033[0m")
time.sleep(0.5)
escrever_devagar("\033[35mEnganei o próximo, assegurando-lhe que uma coisa, na realidade proibida, era boa ou lícita?\033[0m")
time.sleep(1)
print("\n===================================================================================")
print("==================================================================================")
print("------------------------------- FAÇA AS SUAS ANOTAÇÕES ----------------------------")
time.sleep(1.6)
input("APÓS FAZER SUAS ANOTAÇÕES APERTE (ENTER) PARA CONTINUAR")
escrever_devagar("\n======= Ato de Contrição =========")
time.sleep(1)
escrever_devagar("\n\n\033[31mMeu Pai e meu Deus, reconheço com muita dor que pequei!\n Eu vos ofendi, ó meu Redentor, e mereci os vossos castigos. \nPor Maria, minha e vossa Mãe, declaro que não quero pecar mais. \nPor Ela, eu Vos peço perdão\033[0m")
